### ISSUE TITLE
[Suggestion] WebPage For Reader

### ISSUE THREAD

**Issue by Rahulsharma0810** [bregman-arie/devops-exercises#117]
HI, 

This Project is awesome and I really like it, But it lacks readability. especially in the case of new question updates, will it be possible to publish this repo as web/Github Pages? Or publish a page for example every week for new questions only.

Example: https://rahulsharma0810.github.io/devops-exercises/

I used pandoc to generate HTML (with some styles), But there is a challenge of keeping the newest question on top or on a different page.

**Comment by bregman-arie** [comment]
@Rahulsharma0810 The link isn't working for me, can you fix that?

As for readability, I get what you are saying. It's true, this is not a web page or a system, rather a simple markdown. I can't promise it will change anytime soon but I definitely start looking into what we can do to improve readability and overall improve the learning experience. Thank you for your feedback.

I'll keep this issue opened so we can keep developing the idea and discuss the details.

**Comment by Rahulsharma0810** [comment]
@bregman-arie you can check https://rahulsharma0810.github.io/devops-exercises, this is built with https://docsify.js.org/#/, from a single command.

I think docsify is something we can start with.

Thanks,
Rahul Sharma

**Comment by bregman-arie** [comment]
It looks good but still, it's static and requires some maintenance around keeping a page of "new questions". What do you think?

**Comment by Rahulsharma0810** [comment]
I think we need to publish a page every week though diff from a single week, GitHub actions can help us in it to make the process automated.

**Comment by dlccyes** [comment]
Any updates? Why not just use Github page? It's just a few clicks away.(in `settings/pages`). 
Will have to deal with the `/README.md` links in the HTML code and escape `{{}}` tho.

For example, this is the what I just forked and deployed
https://dlccyes.github.io/devops-exercises/

**Comment by bregman-arie** [comment]
@dlccyes how did you associate devops-exercises fork with your user site? (dlccyes.github.io)

**Comment by dlccyes** [comment]
In settings -> pages

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/32875990/200271633-8577d27d-9af9-46ca-bd75-e0700a6113d0.png">

**Comment by bregman-arie** [comment]
I've done exactly that but for some reason it doesn't work

**Comment by dlccyes** [comment]
Well actually it did work, it's just that the job had failed due to `{{}}` not being escaped, as shown in https://github.com/bregman-arie/devops-exercises/actions/runs/3408200210

Now that you've enabled it, I can help with that with a PR when I have time

**Comment by dlccyes** [comment]
Please approve this https://github.com/bregman-arie/devops-exercises/pull/310

**Comment by bregman-arie** [comment]
Thanks! looks good :)
