### ISSUE TITLE
Possible typo and a dead link.

### ISSUE THREAD

**Issue by ksharshveer** [bregman-arie/devops-exercises#125]
Thought I bring attention to these since I came across them.

- The definition for prometheus server reads wrong to me. Rough location: README.md -> Prometheus -> Describe Prometheus component - Server

> Prometheus server responsible for scraping the storing the data

- There is this repo's github link prefixed to what I assume is supposed to be just link to mongodb website. The link is in credits.md file for Mongo logo.

**Comment by bregman-arie** [comment]
Thank you for letting me know :)
