### ISSUE TITLE
Suggestion: Perl topic

### ISSUE THREAD

**Issue by adrianfusco** [bregman-arie/devops-exercises#180]
Maybe we can add some questions related with Perl (Perl, Cpan, DBIx, Mojolicious). It's still used in some projects even in big corporations. What do you think?

Some examples:

- **Perl**
   - What is Perl?
   - Perl data types.
   - Perl operators.
   - What is a Perl subroutine? Different ways to call a Perl subroutine.
   - Lexical and dynamic scoping. Purpose of the `local` and `my` operator.
   - Perl referencing and dereferencing.
   - Perl filehandle.
   - Perl regex.
   - Perl system calls and `open3`.
   - Perl modules. Difference between `.pl` and `.pm` extensions.
- **Perl OOP**
   - How can you define a Perl class? 
   - What is a package? 
   - What is the purpose of the bless function?
   - Perl Inheritance and `SUPER`
   - Method overriding
- **CPAN**
   - What is CPAN? 
   - How to install modules with CPAN?

**Comment by bregman-arie** [comment]
Sure, I'm in favor 👍🏼

**Comment by toby2bee** [comment]
I am willing to learn

**Comment by adrianfusco** [comment]
Perfect.

I did a pull request. I've added new questions with answers. I'll add the missing answers and some exercises.

**Comment by adrianfusco** [comment]
I think we can close this issue. I’ve added the questions and almost all the answers. 

I’ll try to add more questions and exercises asap.
