### ISSUE TITLE
Add basic CI

### ISSUE THREAD

**Issue by bregman-arie** [bregman-arie/devops-exercises#182]
We already have some scripts in the `scripts` directory. It would be good to run them for every PR.
This is also a great task for beginners.

**Comment by Osama-Rashid** [comment]
Hi @bregman-arie 

Could you elaborate what is required? I would really like to contribute on this. Thanks!

**Comment by bregman-arie** [comment]
@Osama-Rashid sure. Using GitHub Actinons, add a workflow to the repository that will run scripts/run_ci.sh every time someone submits a pull request.
More on GitHub Actions here: https://lo-victoria.com/github-actions-101-creating-your-first-workflow

**Comment by Osama-Rashid** [comment]
@bregman-arie  I have created pull request # 190. Kindly review it whenever you find time. Thanks!

**Comment by rafath-100** [comment]
@bregman-arie can you please assign this task to me, I want to solve this issue! I'll create a PR now. kindly review it. Thanks!

**Comment by Poeske117** [comment]
No problems whit Microsoft never but github is spaghetie coding.

**Comment by Shreyasii11** [comment]
hey  I am new here and wanted to build my profile please assign me some task

**Comment by Wbran1957** [comment]
> @Osama-Rashid sure. Using GitHub Actinons, add a workflow to the repository that will run scripts/run_ci.sh every time someone submits a pull request. More on GitHub Actions here: https://lo-victoria.com/github-actions-101-creating-your-first-workflow

**Comment by Wbran1957** [comment]
It is great that you provide opportunity to practice and learn scripting for DevOps here!

**Comment by Warlord77** [comment]
hi i would like to work on this

**Comment by Warlord77** [comment]
@bregman-arie @Wbran1957  https://lo-victoria.com/github-actions-101-creating-your-first-workflow this link doesn't work do you have any alternate link ?

**Comment by Wbran1957** [comment]
Not sure where link is found

**Comment by bregman-arie** [comment]
The link works for me:  https://lo-victoria.com/github-actions-101-creating-your-first-workflow
But you can use any other GitHub Actions tutorial that guides you on how to create CI for GitHub projects.

**Comment by Thubagale** [comment]
Hi, 
could you please help with a  script to monitor AD group changes i.e. if someone is added or removed from an AD group then an email should be sent to a specific email

**Comment by idkburkes** [comment]
Hello, I added a CI workflow as requested. Please review Pull Request #232

**Comment by HamaBarhamou** [comment]
Hi, is this problem already solved or not?

**Comment by bregman-arie** [comment]
> Hi, is this problem already solved or not?

Not yet: https://github.com/bregman-arie/devops-exercises/pull/232

**Comment by MariuszMajcher** [comment]
Hi, this is my first time I get involved in a project. Will try to figure it out!
Cheers for the oportunity!!

**Comment by ayushlohmod** [comment]
hey I am new here i would like to contribute on this please assign me task

**Comment by ayushlohmod** [comment]
Hi! yndue the link is broken can you update the link that would be helpfull

**Comment by orrgato** [comment]
Is this issue still open? I would love to work on this.

**Comment by Artmorse** [comment]
I thiba that this issue needs to be closed.
