### ISSUE TITLE
Found many questions without Answers 

### ISSUE THREAD

**Issue by Krushna-Prasad-Sahoo** [bregman-arie/devops-exercises#200]
Hi @bregman-arie ,

Thanks for the resource. But there a lot of questions unanswered in `devops-exercises/exercises/ansible/README.md`. It would be great if you can add the answers.

Thanks.

**Comment by bregman-arie** [comment]
Hi @Krushna-Prasad-Sahoo 
The whole point of an open source project is that anyone can add answers. I encourage you to try and submit answers to some of the exercises. Don't worry if they are not right, reviews will be provided by me and/or the community :)

**Comment by Krushna-Prasad-Sahoo** [comment]
Thanks a lot @bregman-arie for encouraging, I will sure send you PRs after adding some of the exercises. Thanks.
