### ISSUE TITLE
Question about contribution and merging

### ISSUE THREAD

**Issue by Akseluhr** [bregman-arie/devops-exercises#223]
Hey guys,

We are Aksel and Abdullah, two MSc students at [KTH](https://www.kth.se/en) and we find this open source repo interesting. 

We want to contribute with question related to DevSecOps. More specifically about software supply chain security and dependency management. Our aim is to read research papers and company documentations related to the topics and then formulate relevant questions and answers for this repo. 

Since this is a course project, we need it to be merged due Tuesday 3/5/2022 5 pm CET as of the task deadline. Therefore it would be great if someone could confirm that this is possible (given that the questions and answers we have written are approved).

All the best,
Aksel and Abdullah 

(https://www.linkedin.com/in/aksel-uhr/)
(https://www.linkedin.com/in/abdullahcse/)

**Comment by bregman-arie** [comment]
It is possible and even appreciated :)
Good luck with the project
