### ISSUE TITLE
translation of the project

### ISSUE THREAD

**Issue by HamaBarhamou** [bregman-arie/devops-exercises#239]
Hello everyone, I also propose to start working on the translation of these documents into other languages

**Comment by duskmoon314** [comment]
Is anything new on this? I'm interested in translating to Chinese.

**Comment by bregman-arie** [comment]
> https://github.com/firstcontributions/first-contributions.git

first-contributions, while very popular, is really not that complex to translate. It has a pretty short page to be translated. I don't see how it's manageable with something like devops-exercises where the repo has over 2000 questions. Not saying I'm against translating the repository, just asking how is it even feasible

**Comment by skalibog** [comment]
Hello everyone in this thread, i can help with translating to Ukrainian and Russian.

**Comment by bregman-arie** [comment]
Closing the issue as there is no active work on it nor do I see it's happening anytime soon. My opinion on translating the project remains the same but anyone is more than welcome to try and translate it.
