### ISSUE TITLE
mistake in Linux io redirections question

### ISSUE THREAD

**Issue by pansa** [bregman-arie/devops-exercises#252]
Q:  "Demonstrate Linux stderr to stdout redirection"
has mistake in answer:

" yippiekaiyay 1>&2 "

- it must be  "cmd 2>&1" .   1 = default STDOUT descriptor,  2  = STDERR ,  0 = STDIN

**Comment by akshat084** [comment]
please try "command &> file"

**Comment by bregman-arie** [comment]
FIxed
