### ISSUE TITLE
Want to add more content in AZ-900 section.

### ISSUE THREAD

**Issue by sshiv5768** [bregman-arie/devops-exercises#289]
Hi, I want to contribute in AZ-900 section.

**Comment by bregman-arie** [comment]
Hi @sshiv5768 
It's an open source project. You don't need to open an issue to contribute to the project.
Go for it :)

**Comment by Steve07101** [comment]
I'm new at GitHub and I'm just scratching the surface of coding if it's open source can I check it out?

**Comment by bregman-arie** [comment]
> I'm new at GitHub and I'm just scratching the surface of coding if it's open source can I check it out?

Sure.
