### ISSUE TITLE
no description for 'awk' command (Line 162)

### ISSUE THREAD

**Issue by R-D-Y** [bregman-arie/devops-exercises#374]
Proposition :  

 - awk: a programming language that is mainly used for text processing and data extraction. It can be used to manipulate and modify text in a file:
    - syntax: awk [OPTIONS] [FILTER] [FILE]
extracting a specific field from a CSV file: awk -F ',' '{print $1}' file.csv, output: first field of each line in the file

**Comment by bregman-arie** [comment]
Sounds good. Can you submit a PR?

**Comment by Kaushik-Iyer** [comment]
I can make the PR. Which file's line 162 is mentioned here?

**Comment by R-D-Y** [comment]
Already done (it was on the Linux topic)   :) 

https://github.com/bregman-arie/devops-exercises/blob/master/topics/linux/README.md


![image](https://user-images.githubusercontent.com/102509252/231491321-06239177-85d3-4eb5-98d3-8feb4b5208ca.png)

**Comment by Kaushik-Iyer** [comment]
Okay, I thought it wasn't done since no PR was mentioned, no problem :)

**Comment by R-D-Y** [comment]
PR done last week 

https://github.com/bregman-arie/devops-exercises/pull/378
