### ISSUE TITLE
Add questions on Grafana

### ISSUE THREAD

**Issue by bregman-arie** [bregman-arie/devops-exercises#4]

**Comment by sk3pp3r** [comment]
- What is Grafana?
- Which OS we can install Grafana?
- What to the default HTTP port?
- How we can enforce HTTPS?
- How we can install plugins?
- What is 'Data sources'?

**Comment by bregman-arie** [comment]
Thanks @sk3pp3r

**Comment by AbyelT** [comment]
Hello @bregman-arie, is this issue still open? i would like to contribute

**Comment by AbyelT** [comment]
Great! i will create a pull request when the answers are ready
