### ISSUE TITLE
DevOpsBit Formatting Issues

### ISSUE THREAD

**Issue by zdj21jdz** [bregman-arie/devops-exercises#41]
- Was checking the new DevOpsBit site you created and saw there was some formatting issues w/ the SQL questions I made on the site - Markdown isn't coming through properly, as shown below 

![image](https://user-images.githubusercontent.com/9626723/68953525-152a4c00-0790-11ea-968f-218d73dc2d15.png)

- Additionally, some of the longer questions (such as the ACID definition) aren't showing up because they're so long.

**Comment by zdj21jdz** [comment]
@bregman-arie did you close out your devopsbits website? Went to make a pull request and said the repo didn't exist

**Comment by bregman-arie** [comment]
@zdj21jdz It's open again :) sorry for the inconvenience

**Comment by bregman-arie** [comment]
Let's keep devopsbit issues in devopsbit repo
