### ISSUE TITLE
## Python/Regex fix

### ISSUE THREAD

**Issue by surister** [bregman-arie/devops-exercises#65]
This is a reminder for me or a task if anyone wants :P 

![imagen](https://user-images.githubusercontent.com/37985796/72804757-74ee1900-3c51-11ea-8f86-d7707602f945.png)

Basically, The last two questions aren't really regex's questions.

To do:
- Move said questions to correct place.
- Add new regex questions (Python related!)?
- Maybe add a new ## Regex section, as it is a valuable skill any IT profesional should have.

**Comment by reeshu13489** [comment]
Hi bregman-arie

I would like to contribute for Documentation in python and Ansible. Could you tell me how can I help you .

Regards,
Lumina

**Comment by surister** [comment]
https://github.com/bregman-arie/devops-exercises/blob/master/CONTRIBUTING.md

**Comment by bregman-arie** [comment]
> Hi bregman-arie
> 
> I would like to contribute for Documentation in python and Ansible. Could you tell me how can I help you .
> 
> Regards,
> Lumina

Hi Lumina,

Feel free to submit changes to the repository using pull requests. Anything that you feel improves the way people can learn using the content in this repository.

Let me know if you have any questions.

**Comment by DONMIZKES** [comment]
> This is a reminder for me or a task if anyone wants :P
> 
> ![imagen](https://user-images.githubusercontent.com/37985796/72804757-74ee1900-3c51-11ea-8f86-d7707602f945.png)
> 
> Basically, The last two questions aren't really regex's questions.
> 
> To do:
> 
> * Move said questions to correct place.
> * Add new regex questions (Python related!)?
> * Maybe add a new ## Regex section, as it is a valuable skill any IT profesional should ha
Peretasan rudal, peledakan daerah terbesar manapun, perubahan keadaan sekitar mengambil alih hak milik

**Comment by its-kunal-ssi** [comment]
Is this issue still open

**Comment by gopalnetamnet** [comment]
Chait history

**Comment by gopalnetamnet** [comment]
Chait history

**Comment by gopalnetamnet** [comment]
Hauk

**Comment by Madhavmoudhgal** [comment]
is the issue open 
i would like to work on it

**Comment by inaam33** [comment]
In what file this code is there. I am not able to find the code?

**Comment by surister** [comment]
1º point was solved in https://github.com/bregman-arie/devops-exercises/pull/93 and third is solved as well, since we now have a regex section, the second however could be improved (adding new regex questions).

Closing and opening a new issue regarding the 2º - adding more regex question since there are too few.
